config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#index'
  
  # namespace :admin do
  #   get '/login',    to: 'sessions#new'
  #   post '/login',   to: 'sessions#create'
  #   delete '/logout', to: 'sessions#destroy'
  # end
  
  namespace :parents do
    get '/login',    to: 'sessions#new'
    post '/login',   to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
    resources :requests, :helps
    resources :applies, only: [:index, :destroy]
  end
  
  namespace :children do
    get '/login',    to: 'sessions#new'
    post '/login',   to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
    resources :requests, :helps, only: [:index]
    resources :applies
  end
  
  resources :results
  resources :parents, except: [:index]
  resources :children
  resources :icons
end

app/models/result.rb
class Result < ApplicationRecord
  validates :completion_date, presence: true
  validates :name, presence: true, length: { maximum: 50 }
  validates :description, length: { maximum: 255 }
  validates :point, presence: true
  validates :bonus, presence: true
  
  belongs_to :parent
  belongs_to :child
  belongs_to :apply
  
  def start_time
    self.completion_date
  end
  
  def create_result(apply)
    self.child_id = apply.request.child_id
    self.appeal_comment = apply.comment
    self.apply_id = apply.id
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :logged_in_parent_or_child
  before_action :correct_parent_for_results, only:[:edit, :update, :destroy]
  
  def new
    # ポイント承認ページ
    # @result = Result.new
    @result = current_parent.results.build
    if params[:apply_id] != nil
      @apply = Apply.find_by(id: params[:apply_id])
      render "results/approval_new"
    # ポイント登録ページ
    elsif params[:help_id] != nil
      @help = Help.find_by(id: params[:help_id])
      render "results/direct_new"
    end
  end
  
  def create
    # @result = Result.new(result_params)
    # @result.parent_id = current_parent.id
    @result = current_parent.results.build(result_params)
    # ポイント承認処理
    if @apply = Apply.find_by(id: params[:result][:apply_id])
      # @result.child_id = @apply.request.child_id
      # @result.appeal_comment = @apply.comment
      # @result.apply_id = @apply.id
      @result.create_result(@apply)
      begin
        Result.transaction do
          Apply.transaction do
            @result.save!
            @apply.update_attributes!(close: true)
          end
        end
        redirect_to parents_applies_path, success: "承認が完了しました"
      rescue => e
        flash.now[:danger] = "承認に失敗しました"
        render :approval_new
      end
    # ポイントを直接登録する処理
    elsif @help = Help.find_by(id: params[:result][:help_id])
      # @request = Request.new(
      #   name: @help.name, 
      #   description: @help.description, 
      #   point: @help.point, 
      #   parent_id: @help.parent_id, 
      #   child_id: @help.child_id,
      #   request_date: @result.completion_date,
      #   status: true)
      request = Request.new()
      request.create_request(@help, @result.completion_date)
      # @apply = Apply.new(
      #   comment: "",
      #   completion_date: @result.completion_date,
      #   close: true)
      apply = Apply.new()
      create_apply_date = @result.completion_date
      apply.create_apply(create_apply_date)
      begin
        Request.transaction do
          Apply.transaction do
            Result.transaction do
              request.save!
              apply.request_id = request.id
              apply.save!
              # @result.child_id = @help.child_id
              # @result.appeal_comment = apply.comment
              # @result.apply_id = apply.id
              @result.create_result(apply)
              @result.save!
            end
          end
        end
        redirect_to parents_helps_path, success: "ポイント登録が完了しました"
      rescue => e
        flash.now[:danger] = "ポイント登録に失敗しました"
        render :direct_new
      end
    end
  end
  
  def edit
    @result = Result.find(params[:id])
  end
  
  def update
    @result = Result.find(params[:id])
    if @result.update_attributes(result_params)
      redirect_to results_path, success: "ポイントを変更しました"
    else
      flash.now[:danger] = "ポイントの変更に失敗しました"
      render :edit
    end
  end

  def index
    if parent_logged_in?
      @children = current_parent.children.includes(:icon)
      @applies = current_parent.applies.where(close: false)
      @results = current_parent.results.order(child_id: "ASC").includes(:child)
      parent = current_parent
    elsif child_logged_in?
      @children = current_child.parent.children.includes(:icon)
      @requests = current_child.requests.where(status: false)
      @results = current_child.parent.results.order(child_id: "ASC").includes(:child)
      parent = current_child.parent
    end
    
    displays = {}
    @results.each do |result|
      if displays.key?(result.completion_date)
        if displays[result.completion_date].exclude?(result.child)
          displays[result.completion_date].push(result.child)
        end
      else
        displays[result.completion_date] = [result.child]
      end
    end

    @display_children = []
    displays.each do |k,v|
      struct = Struct.new("Display",:start_time, :child) 
      @display_children.push(struct.new(k, v))
    end
    
    if params[:start_date]
      search_date = params[:start_date]
    else
      search_date = Date.today
    end
    @search_month = search_date.to_date
    
    month_beginning = @search_month.beginning_of_month.strftime("%Y-%m-%d")
    month_end = @search_month.end_of_month.strftime("%Y-%m-%d")
    query = <<~QUERY
      SELECT SUM(results.point + results.bonus) AS "total_point", child_id 
      FROM results 
      WHERE parent_id = #{parent.id} AND results.completion_date
      BETWEEN '#{month_beginning}' AND '#{month_end}'
      GROUP BY child_id 
    QUERY
    points_data = ActiveRecord::Base.connection.select_all(query)
    points = points_data.to_a
    point_data_hash = {}
    points.each do |point|
      point_data_hash[point["child_id"]] = point["total_point"]
    end
    @children.each do |child|
      if point_data_hash.has_key?(child.id)
        child.total_point = point_data_hash[child.id]
      else
        child.total_point = 0
      end
    end
    
    
    if params[:date]
      @date = params[:date]
      render "results/result_day"
    else
      render "results/result_month"
    end
  end
  
  # def show
    # if parent_logged_in?
    #   @children = current_parent.children
    #   # @results = current_parent.results.where(completion_date: @date)
    # elsif child_logged_in?
    #   @children = current_child.parent.children
    #   # @results = current_child.parent.results.where(completion_date: @date)
    # end
  # end
  
  def destroy
    result = Result.find(params[:id])
    request = result.apply.request
    apply = result.apply
    Request.transaction do
      Apply.transaction do
        Result.transaction do
          request.destroy!
          apply.destroy!
          result.destroy!
        end
      end
    end
    redirect_to root_path, success: 'お手伝い実績を削除しました'
  end
  
   private
  def result_params
    params.require(:result).permit(:name, :description, :point, :bonus, :completion_date, :parents_comment)
  end
  
  #beforeアクション
  # ログイン済parentまたはchildどうか確認
  def logged_in_parent_or_child
    unless parent_logged_in? || child_logged_in?
      flash[:danger] = "ログインが必要です"
        redirect_to root_path
    end
  end
  
  # requestに対して正しいparentかどうか確認
  def correct_parent_for_results
    @result = Result.find_by(id: params[:id])
    redirect_to(results_path) unless correct_parent_for_model?(@result)
  end
  
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/results/_result_day.html.erb
<div class="result-show-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-1 col-md-10 result-show-container">
        <h1 class="text-center text-color"><%= @date %> お手伝い一覧</h1>
        <% @children.each do |child|%>
          <% if child.results.where(completion_date: @date).count != 0 %>
            <p class="text-color">お手伝いした人：<%= child.name %></p>
            <table class="text-center text-color">
              <tr>
                <th>お手伝い名</th>
                <th>説明</th>
                <th>ポイント</th>
                <th>ボーナス</th>
                <th>アピールポイント</th>
                <th>コメント</th>
                <th></th>
                <th></th>
              </tr>
              <% child.results.where(completion_date: @date).each do |result|%>
                <tr>
                  <td><%= result.name %></td>
                  <td><%= safe_join(result.description.split("\n"), tag(:br)) %></td>
                  <td><%= result.point %>pt</td>
                  <td><%= result.bonus %>pt</td>
                  <td><%= safe_join(result.appeal_comment.split("\n"), tag(:br)) %></td>
                  <td><%= safe_join(result.parents_comment.split("\n"), tag(:br)) %></td>
                  <td><%= link_to "編集", edit_result_path(result.id) %></td>
                  <td><%= link_to "削除", result_path(result.id), method: :delete %></td>
                </tr>
              <% end %>
            </table>
          <% end %>
        <% end %>
        <%= link_to "戻る", results_path, class:'text-color' %>
      </div>
    </div>
  </div>
</div>

app/views/results/approval_new.html.erb
<div class="result-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 result-new-container">
        <h1 class="text-center text-color"><%= @apply.request.child.name %>のお手伝い承認</h1>
        <%= form_with model: @result, local: true do |f| %>
          <%= render 'shared/error_messages', {model: @result} %>
          <%= f.hidden_field :apply_id, value: @apply.id %>
          <div class="form-group">
            <%= f.label :completion_date, "お手伝いした日", class: 'text-color' %>
            <%= f.date_field :completion_date, value: @apply.completion_date, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :name, "お手伝い名", class: "text-color" %>
            <%= f.text_field :name, value: @apply.request.name, class: "form-control"  %>
          </div>
          <div class="form-group">
            <%= f.label :description, "説明", class: "text-color" %>
            <%= f.text_area :description, value: @apply.request.description, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :point, "ポイント（半角数字）", class: "text-color" %>
            <%= f.number_field :point, value: @apply.request.point, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :bonus, "ボーナスポイント（半角数字）", class: "text-color" %>
            <%= f.number_field :bonus, value: 0, class: "form-control" %>
          </div>
          <div class="form-group">
            <p>アピールポイント</p>
            <% if @apply.comment != "" %>
              <p><%= safe_join(@apply.comment.split("\n"), tag.br) %></p>
            <% else %>
              <p>-------</p>
            <% end %>  
          </div>
          <div class="form-group">
            <%= f.label :parents_comment, "コメント", class: "text-color" %>
            <%= f.text_area :parents_comment, class: "form-control" %>
          </div>
          <%= f.submit "登録", class: "btn-block btn-color" %>
        <% end %>
        <%= link_to "戻る", parents_helps_path, class: "text-color" %>
      </div>
    </div>
  </div>
</div>

app/views/results/direct_new.html.erb
<div class="result-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 result-new-container">
        <h1 class="text-center text-color"><%= @help.child.name %>のポイント登録</h1>
        <%= form_with model: @result, local: true do |f| %>
          <%= render 'shared/error_messages', {model: @result} %>
          <%= f.hidden_field :help_id, value: @help.id %>
          <div class="form-group">
            <%= f.label :completion_date, "お手伝いした日", class: 'text-color' %>
            <%= f.date_field :completion_date, value: Date.today, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :name, "お手伝い名", class: "text-color" %>
            <%= f.text_field :name, value: @help.name, class: "form-control"  %>
          </div>
          <div class="form-group">
            <%= f.label :description, "説明", class: "text-color" %>
            <%= f.text_area :description, value: @help.description, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :point, "ポイント（半角数字）", class: "text-color" %>
            <%= f.number_field :point, value: @help.point, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :bonus, "ボーナスポイント（半角数字）", class: "text-color" %>
            <%= f.number_field :bonus, value: 0, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :parents_comment, "コメント", class: "text-color" %>
            <%= f.text_area :parents_comment, class: "form-control" %>
          </div>
          <%= f.submit "ポイントを登録する", class: "btn-block btn-color" %>
        <% end %>
        <%= link_to "戻る", parents_helps_path, class: "text-color" %>
      </div>
    </div>
  </div>
</div>

app/views/results/edit.html.erb
<div class="result-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 result-new-container">
        <h1 class="text-center text-color"><%= @result.child.name %>のポイント編集</h1>
        <%= form_with model: @result, local: true do |f| %>
          <div class="form-group">
            <%= f.label :completion_date, "お手伝いした日", class: 'text-color' %>
            <%= f.date_field :completion_date, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :name, "お手伝い名", class: "text-color" %>
            <%= f.text_field :name, class: "form-control"  %>
          </div>
          <div class="form-group">
            <%= f.label :description, "説明", class: "text-color" %>
            <%= f.text_area :description, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :point, "ポイント（半角数字）", class: "text-color" %>
            <%= f.number_field :point, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :bonus, "ボーナスポイント（半角数字）", class: "text-color" %>
            <%= f.number_field :bonus, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :parents_comment, "コメント", class: "text-color" %>
            <%= f.text_area :parents_comment, class: "form-control" %>
          </div>
          <%= f.submit "ポイントを登録する", class: "btn-block btn-color" %>
        <% end %>
        <%= link_to "戻る", parents_helps_path, class: "text-color" %>
      </div>
    </div>
  </div>
</div>

app/views/results/result_day.html.erb
<div class="result-day-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-1 col-md-10 result-day-container">
        <h1 class="text-center text-color"><%= @date %> お手伝い一覧</h1>
        <% @children.each do |child|%>
          <% if child.match_completion_date(@date).length != 0 %>
            <p class="text-color">お手伝いした人：<%= child.name %></p>
            <table class="text-center text-color">
              <tr>
                <th class="text-center col-md-2">お手伝い名</th>
                <th class="text-center col-md-2">説明</th>
                <th class="text-center col-md-1">ポイント</th>
                <th class="text-center col-md-1">ボーナス</th>
                <th class="text-center col-md-2">アピールポイント</th>
                <th class="text-center col-md-2">コメント</th>
                <th class="col-md-1"></th>
                <th class="col-md-1"></th>
              </tr>
              <% child.match_completion_date(@date).each do |result|%>
                <tr>
                  <td><%= result.name %></td>
                  <td class="text-left"><%= safe_join(result.description.split("\n"), tag.br) %></td>
                  <td><%= result.point %>pt</td>
                  <td><%= result.bonus %>pt</td>
                  <td class="text-left"><%= safe_join(result.appeal_comment.split("\n"), tag.br) %></td>
                  <td class="text-left"><%= safe_join(result.parents_comment.split("\n"), tag.br) %></td>
                  <td><%= link_to "編集", edit_result_path(result.id) %></td>
                  <td><%= link_to "削除", result_path(result.id), method: :delete, data: { confirm: '削除しますか？'} %></td>
                </tr>
              <% end %>
            </table>
          <% end %>
        <% end %>
        <%= link_to "戻る", results_path, class:'text-color' %>
      </div>
    </div>
  </div>
</div>

app/views/results/result_month.html.erb
<div class="result-month-wrapper">
  <div class="container">
    <div class="row">
      <div class="result-month-container">
        <div class="sign-container">
          <% if parent_logged_in? && @applies.length != 0%>
            <%= link_to "承認待ちお手伝いがあります", parents_applies_path %>
          <% elsif child_logged_in? && @requests.length != 0 %>
            <%= link_to "お手伝いを頼まれています", children_requests_path %>
          <% end%>
        </div>
        <div class="text-color point-container">
          <h2><%= @search_month.month %>月のポイント</h2>
          
          <% @children.each do |child|%>
            <div class="child-point">
              <%= image_tag child.icon.image.url %>
              <p class="text-right child-name"><%= child.name %></p>
              <p>：</p>
              <p><%= child.total_point %>pt</p>
            </div>
          <% end %>
        </div>
        
        <%= month_calendar events: @display_children do |date, display_children| %>
          <%= date.day %>
          
          <% display_children.each do |display_child| %>
            <% display_child.child.each do |child| %>
              <%= link_to results_path(date: display_child.start_time ) do %>
                <%= image_tag child.icon.image.url %> 
              <% end %>
            <% end %>
          <% end %>
          
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/results/show.html.erb
<div class="result-show-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-1 col-md-10 result-show-container">
        <h1 class="text-center text-color"><%= @date %> お手伝い一覧</h1>
        <% @children.each do |child|%>
          <% if child.results.where(completion_date: @date).count != 0 %>
            <p class="text-color">お手伝いした人：<%= child.name %></p>
            <table class="text-center text-color">
              <tr>
                <th>お手伝い名</th>
                <th>説明</th>
                <th>ポイント</th>
                <th>ボーナス</th>
                <th>アピールポイント</th>
                <th>コメント</th>
                <th></th>
                <th></th>
              </tr>
              <% child.results.where(completion_date: @date).each do |result|%>
                <tr>
                  <td><%= result.name %></td>
                  <td><%= safe_join(result.description.split("\n"), tag(:br)) %></td>
                  <td><%= result.point %>pt</td>
                  <td><%= result.bonus %>pt</td>
                  <td><%= safe_join(result.appeal_comment.split("\n"), tag(:br)) %></td>
                  <td><%= safe_join(result.parents_comment.split("\n"), tag(:br)) %></td>
                  <td><%= link_to "編集", edit_result_path(result.id) %></td>
                  <td><%= link_to "削除", result_path(result.id), method: :delete %></td>
                </tr>
              <% end %>
            </table>
          <% end %>
        <% end %>
        <%= link_to "戻る", results_path, class:'text-color' %>
      </div>
    </div>
  </div>
</div>