config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#index'
  
  # namespace :admin do
  #   get '/login',    to: 'sessions#new'
  #   post '/login',   to: 'sessions#create'
  #   delete '/logout', to: 'sessions#destroy'
  # end
  
  namespace :parents do
    get '/login',    to: 'sessions#new'
    post '/login',   to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
    resources :requests, :helps
    resources :applies, only: [:index, :destroy]
  end
  
  namespace :children do
    get '/login',    to: 'sessions#new'
    post '/login',   to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
    resources :requests, :helps, only: [:index]
    resources :applies
  end
  
  resources :results
  resources :parents, except: [:index]
  resources :children
  resources :icons
end

app/models/apply.rb
class Apply < ApplicationRecord
  validates :close, inclusion: { in:[true, false] }
  validates :completion_date, presence: true
  
  belongs_to :request
  has_one :result, dependent: :destroy
  has_one :child, through: :request
  
  # def closed
  #   self.close
  # end
  
  def create_apply(create_apply_date)
    self.comment = ""
    self.completion_date = create_apply_date
    self.close = true
  end
end

app/controllers/children/applies_controller.rb
class Children::AppliesController < ApplicationController
  before_action :logged_in_child
  before_action :correct_child_for_applies, only:[:edit, :update, :destroy]
  
  def new
    @apply = Apply.new
    # リクエストからのお手伝い報告
    if params[:request_id] != nil
      @request = Request.find_by(id: params[:request_id])
      render "children/applies/from_request_new"
    # お手伝いリストからのお手伝い報告
    elsif params[:help_id] != nil
      @help = Help.find_by(id: params[:help_id])
      render "children/applies/direct_new"
    end
  end
  
  def create
    @apply = Apply.new(apply_params)
    # リクエストからのお手伝い報告
    if @request = Request.find_by(id: params[:apply][:request_id])
      @apply.request_id = params[:apply][:request_id]
      begin
        Apply.transaction do
          Request.transaction do
            @apply.save!
            @request.update_attributes!(status: true)
          end
        end
        redirect_to children_requests_path, success: "ママ・パパに報告しました"
      rescue => e
        flash.now[:danger] = "報告が失敗しました"
        render :from_request_new
      end
     # お手伝いリストからのお手伝い報告
    elsif @help = Help.find_by(id: params[:apply][:help_id])
      # @request = Request.new(
      #   name: @help.name, 
      #   description: @help.description, 
      #   point: @help.point, 
      #   parent_id: @help.parent_id, 
      #   child_id: @help.child_id,
      #   request_date: @apply.completion_date,
      #   status: true)
      request = Request.new()
      request.create_request(@help, @apply.completion_date)
      @apply.direct = true
      begin
          Request.transaction do
            Apply.transaction do
              request.save!
              @apply.request_id = request.id
              @apply.save!
            end
        end
        redirect_to children_helps_path, success: "ママ・パパに報告しました"
      rescue => e
        flash.now[:danger] = "報告が失敗しました"
        render :direct_new
      end
    end
  end
  
  def edit
    # @apply = Apply.find(params[:id])
    @request = @apply.request
  end
  
  def update
    # @apply = Apply.find(params[:id])
    @request = @apply.request
    if @apply.update_attributes(apply_params)
      redirect_to children_applies_path, success: "お手伝い報告を変更しました"
    else
      flash.now[:danger] = "お手伝い報告の変更に失敗しました"
      render :edit
    end
  end

  def index
    @applies = current_child.applies.where(close: false).includes(:request)
  end
  
  def destroy
    apply = Apply.find(params[:id])
    request = apply.request
    if apply.direct == false
      Apply.transaction do
        Request.transaction do
          apply.destroy!
          request.update_attributes!(status: false)
        end
      end
    else
      Apply.transaction do
        Request.transaction do
          apply.destroy!
          request.destroy!
        end
      end
    end
    redirect_to children_applies_path, success: '報告をやめました'
  end
  
   private
  def apply_params
    params.require(:apply).permit(:comment, :completion_date)
  end
  
  # applyに対して正しいchildかどうか確認
  def correct_child_for_applies
    @apply = Apply.find_by(id: params[:id])
    redirect_to(children_applies_path) unless @apply && correct_child_for_model?(@apply.request)
  end
end

app/controllers/children/helps_controller.rb
class Children::HelpsController < ApplicationController
  before_action :logged_in_child
  
  def index
    @helps = current_child.helps
  end
end

app/controllers/children/requests_controller.rb
class Children::RequestsController < ApplicationController
  before_action :logged_in_child
  
  def index
    @requests = current_child.requests.where(status: false)
  end
end

app/controllers/children/sessions_controller.rb
class Children::SessionsController < ApplicationController
  before_action :logged_out_parent_and_child, only:[:new, :create]
  
  def new
  end
  
  def create
    child = Child.find_by(login_id: params[:session][:login_id])
    if child && child.authenticate(params[:session][:password])
      log_in_child child
      redirect_to results_path, success: "ログインに成功しました"
    else
      flash.now[:danger] = "ログインに失敗しました"
      render :new
    end
  end
  
  def destroy
    log_out_child
    redirect_to root_path, info: "ログアウトしました"
  end
  
end

app/controllers/children_controller.rb
class ChildrenController < ApplicationController
  before_action :logged_in_parent
  before_action :correct_parent_for_child, only:[:edit, :update, :destroy]
  
  def new
    # @child = Child.new
    @child = current_parent.children.build
    @icons = Icon.all
  end
  
  def create
    # @child = Child.new(child_params)
    # @child.parent_id = current_parent.id
    @child = current_parent.children.build(child_params)
    @icons = Icon.all
    if @child.save
      redirect_to children_path, success: "登録が完了しました"
    else
      flash.now[:danger] = "登録に失敗しました"
      render :new
    end
  end

  def edit
    @child = Child.find(params[:id])
    @icons = Icon.all
  end
  
  def update
    @child = Child.find(params[:id])
    @icons = Icon.all
    # if @child.update_attributes(child_params)
    #   redirect_to children_path, success: "お子さま情報を変更しました"
    # else
    #   flash.now[:danger] = "お子さま情報の変更に失敗しました"
    #   render :edit
    # end
    
    if params[:child][:change_password] == "true"
      if @child.authenticate(params[:child][:current_password]) && @child.update_attributes(child_params)
        redirect_to children_path, success: "お子さま情報を変更しました"
      else
        flash.now[:danger] = "お子さま情報の変更に失敗しました"
        render :edit
      end
    else
      if @child.update_attributes(child_params)
        redirect_to children_path, success: "お子さま情報を変更しました"
      else
        flash.now[:danger] = "お子さま情報の変更に失敗しました"
        render :edit
      end
    end  
  end

  def index
    @children = current_parent.children
  end
  
  def destroy
    Child.find_by(id: params[:id]).destroy
    redirect_to children_path, success: 'お子さまの名前を削除しました'
  end
  
  private
  def child_params
    params.require(:child).permit(:name, :login_id, :password, :password_confirmation, :icon_id)
  end
  
  # beforeアクション
  
  # childに対して正しいparentかどうか確認
  def correct_parent_for_child
    @child = Child.find_by(id: params[:id])
    redirect_to(children_path) unless @child && @child.parent == current_parent
  end
end

app/controllers/parents/applies_controller.rb
class Parents::AppliesController < ApplicationController
  before_action :logged_in_parent
  before_action :correct_parent_for_applies, only:[:destroy]
  
  def index
    @applies = current_parent.applies.where(close: false).includes(:child)
    # @children = current_parent.children
    @children = []
    @applies.each do |apply|
      if @children.exclude?(apply.child)
        @children.push(apply.child)
      end
    end
  end
  
  def destroy
    # apply = Apply.find_by(id: params[:id])
    request = @apply.request
    Apply.transaction do
      Request.transaction do
        @apply.destroy!
        request.update_attributes(status: false)
      end
    end
    redirect_to parents_applies_path, success: '承認を却下しました'
  end
  
  # beforeアクション
  
  # applyに対して正しいparentかどうか確認
  def correct_parent_for_applies
    @apply = Apply.includes(:child).find_by(id: params[:id])
    redirect_to(parents_applies_path) unless @apply && correct_parent_for_model?(@apply.request)
  end
end

app/helpers/children/applies_helper.rb
module Children::AppliesHelper
end

app/helpers/children/helps_helper.rb
module Children::HelpsHelper
end

app/helpers/children/requests_helper.rb
module Children::RequestsHelper
end

app/helpers/children/sessions_helper.rb
module Children::SessionsHelper
  
  def log_in_child(child)
    session[:child_id] = child.id
  end
  
  def current_child
    @current_child ||=Child.find_by(id: session[:child_id])
  end
  
  def child_logged_in?
    !current_child.nil?
  end
  
  def log_out_child
    session.delete(:child_id)
    @current_child = nil
  end
  
  #beforeアクション
  # ログイン済childかどうか確認
  def logged_in_child
    unless child_logged_in?
      flash[:danger] = "子アカウントのログインが必要です"
      if parent_logged_in?
        redirect_to results_path
      else
        redirect_to children_login_path
      end
    end
  end
  
  # 渡されたmodelのchildがログイン済childであればtrueを返す
  def correct_child_for_model?(model)
    model.child == current_child
  end
end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/helpers/parents/applies_helper.rb
module Parents::AppliesHelper
end

app/views/children/applies/direct_new.html.erb
<div class="apply-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 apply-new-container">
        <h1 class="text-center text-color">お手伝い報告</h1>
        <%= form_with(model: [ :children, @apply ], local: true) do |f| %>
          <%= render 'shared/error_messages', {model: @apply} %>
          <%= f.hidden_field :help_id, value: @help.id %>
          <div class="form-group">
            <%= f.label :completion_date, "お手伝いした日", class: 'text-color' %>
            <%= f.date_field :completion_date, value: Date.today, class: "form-control" %>
          </div>
          <div class="form-group">
            <table>
              <tr>
                  <th>お手伝い名</th>
                  <th>説明</th>
                  <th>ポイント</th>
                </tr>
              <tr>
                <td><%= @help.name %></td>
                <td><%= safe_join(@help.description.split("\n"), tag.br) %></td>
                <td><%= @help.point %></td>
              </tr>
            </table>
          </div>
          <div class="form-group">
            <%= f.label :comment, "アピールポイント", class: "text-color" %>
            <%= f.text_area :comment, class: "form-control" %>
          </div>
          <%= f.submit "報告", class: "btn-block btn-color" %>
        <% end %>
        <%= link_to "戻る", "#", class: "text-color" %>
      </div>
    </div>
  </div>
</div>

app/views/children/applies/edit.html.erb
<div class="apply-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 apply-new-container">
        <h1 class="text-center text-color">お手伝い報告編集</h1>
        <%= form_with(model: [ :children, @apply ], local: true) do |f| %>
          <%= render 'shared/error_messages', {model: @apply} %>
          <div class="form-group">
            <%= f.label :completion_date, "お手伝いした日", class: 'text-color' %>
            <%= f.date_field :completion_date, class: "form-control" %>
          </div>
          <div class="form-group">
            <table>
              <tr>
                  <th>お手伝い名</th>
                  <th>説明</th>
                  <th>ポイント</th>
                </tr>
              <tr>
                <td><%= @request.name %></td>
                <td><%= safe_join(@request.description.split("\n"), tag(:br)) %></td>
                <td><%= @request.point %></td>
              </tr>
            </table>
          </div>
          <div class="form-group">
            <%= f.label :comment, "アピールポイント", class: "text-color" %>
            <%= f.text_area :comment, class: "form-control" %>
          </div>
          <%= f.submit "変更する", class: "btn-block btn-color" %>
        <% end %>
        <%= link_to "戻る", "#", class: "text-color" %>
      </div>
    </div>
  </div>
</div>

app/views/children/applies/from_request_new.html.erb
<div class="apply-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 apply-new-container">
        <h1 class="text-center text-color">お手伝い報告</h1>
        <%= form_with(model: [ :children, @apply ], local: true) do |f| %>
          <%= render 'shared/error_messages', {model: @apply} %>
          <%= f.hidden_field :request_id, value: @request.id %>
          <div class="form-group">
            <%= f.label :completion_date, "お手伝いした日", class: 'text-color' %>
            <%= f.date_field :completion_date, value: @request.request_date, class: "form-control" %>
          </div>
          <div class="form-group">
            <table>
              <tr>
                  <th>お手伝い名</th>
                  <th>説明</th>
                  <th>ポイント</th>
                </tr>
              <tr>
                <td><%= @request.name %></td>
                <td><%= safe_join(@request.description.split("\n"), tag(:br)) %></td>
                <td><%= @request.point %></td>
              </tr>
            </table>
          </div>
          <div class="form-group">
            <%= f.label :comment, "アピールポイント", class: "text-color" %>
            <%= f.text_area :comment, class: "form-control" %>
          </div>
          <%= f.submit "報告", class: "btn-block btn-color" %>
        <% end %>
        <%= link_to "戻る", "#", class: "text-color" %>
      </div>
    </div>
  </div>
</div>

app/views/children/applies/index.html.erb
<div class="applies-index-wrapper">
  <div class="container">
      <div class="row">
        <div class="col-md-offset-1 col-md-10 applies-index-container">
          <h1 class="text-center text-color">報告中のお手伝い</h1>
            <% if @applies.length != 0 %>
              <table class="text-center text-color table-hover">
                <tr>
                  <th class="text-center col-md-1 table-date">頼まれた日</th>
                  <th class="text-center col-md-1 table-date">お手伝い日</th>
                  <th class="text-center col-md-2">お手伝い名</th>
                  <th class="text-center col-md-2">説明</th>
                  <th class="text-center col-md-1">ポイント</th>
                  <th class="text-center col-md-3">アピールポイント</th>
                  <th class="col-md-1"></th>
                  <th class="col-md-1"></th>
                </tr>
                <% @applies.each do |apply|%>
                  <tr>
                    <td><%= apply.request.request_date.strftime("%-m/%-d") %></td>
                    <td><%= apply.completion_date.strftime("%-m/%-d") %></td>
                    <td class="text-left"><%= apply.request.name %></td>
                    <td class="text-left"><%= safe_join(apply.request.description.split("\n"), tag.br) %></td>
                    <td><%= apply.request.point %>pt</td>
                    <td class="text-left"><%= safe_join(apply.comment.split("\n"), tag.br) %></td>
                    <td><%= link_to "編集", edit_children_apply_path(apply.id) %></td>
                    <td><%= link_to "取り消し", children_apply_path(apply.id), method: :delete, data: { confirm: 'お手伝いの報告をやめますか？'} %></td>
                  </tr>
                <% end %>
              </table>
            <% else %>
              <p class="text-color">報告中のお手伝いはありません</p>
            <% end %>
        </div>
      </div>
  </div>
</div>