config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#index'
  
  # namespace :admin do
  #   get '/login',    to: 'sessions#new'
  #   post '/login',   to: 'sessions#create'
  #   delete '/logout', to: 'sessions#destroy'
  # end
  
  namespace :parents do
    get '/login',    to: 'sessions#new'
    post '/login',   to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
    resources :requests, :helps
    resources :applies, only: [:index, :destroy]
  end
  
  namespace :children do
    get '/login',    to: 'sessions#new'
    post '/login',   to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
    resources :requests, :helps, only: [:index]
    resources :applies
  end
  
  resources :results
  resources :parents, except: [:index]
  resources :children
  resources :icons
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
<% end %>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-default navbar-fixed-top navbar-transparent">
    <div class="container">
      <%= link_to root_path do %>
        <%= icon 'fas', 'home fa-3x', class: "navbar-home"  %>
      <% end %>
      <!--<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContents" aria-controls="navbarContents" aria-expanded="false" aria-label="Toggle navigation">-->
      <!--  <span class="navbar-toggler-icon"></span>-->
      <!--</button>-->
        <div class="collapse navbar-collapse navbar-right" id="navbarContents">
          <ul class="nav navbar-nav">
          <% if parent_logged_in? %>
            <li class="nav-item help-menu">
              <!--<div class="dropdown">-->
                <%#= link_to "お手伝い管理", parents_helps_path %>
                <!--<button type="button" id="dropdown-help" class="btn btn-secondary dropdown-toggle text-color" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">お手伝い管理</button>-->
                  <%= link_to "お手伝い管理", "#", class:"btn header-btn dropdown-toggle text-color", "id":"dropdown-help", "data-toggle":"dropdown", "aria-haspopup":"true", "aria-expanded":"false" %>
                  <div class="dropdown-menu" aria-labelledby="dropdown-help">
                    <ul class="help-list">
                      <li>
                        <%= link_to "お手伝い登録", new_parents_help_path, class:'dropdown-item text-color' %>
                      </li>
                      <li>
                        <%= link_to "お手伝い一覧", parents_helps_path, class:'dropdown-item text-color' %>
                      </li>
                      <li>
                        <%= link_to "依頼中のお手伝い", parents_requests_path, class:'dropdown-item text-color' %>
                      </li>
                      <li>
                        <%= link_to "承認待ちのお手伝い", parents_applies_path, class:'dropdown-item text-color' %>
                      </li>
                    </ul>
                </div>
              <!--</div>-->
            </li>
            <li class="nav-item">
              <%= link_to "こども管理",  children_path, class:'btn header-btn text-color' %>
            </li>
            <li class="nav-item">
              <%= link_to "アカウント設定", edit_parent_path(current_parent), class:'btn header-btn text-color' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", parents_logout_path, method: :delete, class:'btn header-btn text-color' %>
            </li>
          <% elsif child_logged_in? %>
            <li class="nav-item">
              <%= image_tag current_child.icon.image.url %>
            </li>
            <li class="nav-item">
              <p><%= current_child.name %></p>
            </li>
            <li class="nav-item">
              <%= link_to "お手伝いをする", children_helps_path, class:'btn header-btn text-color' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", children_logout_path, method: :delete, class:'btn header-btn text-color' %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "新規登録", new_parent_path, class:'btn header-btn text-color' %>
            </li>
            <li class="nav-item">
              <%= link_to "ママ・パパのログイン", parents_login_path, class:'btn header-btn text-color' %>
            </li>
            <li class="nav-item">
              <%= link_to "こどものログイン", children_login_path, class:'btn header-btn text-color' %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_javascript_file.html.erb
<script>
  $(function(){
    $(".alert").fadeOut(5000);
  });
</script>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<link href="https://fonts.googleapis.com/css?family=M+PLUS+Rounded+1c" rel="stylesheet">
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelpPoint</title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/flash_messages' %>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/javascript_file' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>